# Generated by Django 4.2.8 on 2024-01-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_stock",
            field=models.IntegerField(null=True),
        ),
    ]
