# Generated by Django 4.2.8 on 2024-01-02 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_product_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_image",
        ),
    ]
