# Generated by Django 4.2.8 on 2024-01-10 01:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_delete_customuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="location",
            new_name="shipping_address",
        ),
    ]
