# Generated by Django 4.2.8 on 2024-01-02 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_product_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_stock",
            new_name="stock",
        ),
    ]
